add goodbye step

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -12,8 +12,8 @@ jobs:
     steps:
        - name: Fail Step
          run: |
-          "echo Fail State"
-           exit 1      
+          echo "Fail State"
+          exit 1      
 
 
     
